#!/bin/bash

#SBATCH --job-name=spSOULGPU                  # Descriptive job name
#SBATCH --time=00:10:00                       # Maximum wall time (hh:mm:ss)
#SBATCH --nodes=1                             # Number of nodes to use
#SBATCH --ntasks-per-node=1                   # Number of MPI tasks per node (e.g., 1 per GPU)
#SBATCH --cpus-per-task=1                     # Number of CPU cores per task (adjust as needed)
#SBATCH --gres=gpu:4                          # Number of GPUs per node (adjust to match hardware)
#SBATCH --partition=boost_usr_prod            # GPU-enabled partition
#SBATCH --qos=boost_qos_dbg                   # Quality of Service
#SBATCH --output=speculaJobSOULGPU.out        # File for standard output
#SBATCH --error=speculaJobSOULGPU.err         # File for standard error
#SBATCH --account=try25_rossi                 # Project account number

module load cuda/12.3                         # Load CUDA toolkit
module load openmpi/4.1.6--nvhpc--23.11       # Load MPI implementation
module load nvhpc/23.11

srun --mpi=none bash -c "specula --mpi $WORK/SPECULA/config/SOUL/params_pyr_soul.yml $WORK/SPECULA/config/leonardo/overrides/ov_SOUL_GPU_leonardo.yml"

